import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import "./globals.scss"
import {Header} from "@/widgets/Header/Header"
import {Footer} from "@/widgets/Footer/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next"

const roboto = Roboto({
  weight: ["300", "400", "700", "900"],
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "МедЭксперт",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={roboto.className}>
    <Header />
    <main>
      {children}
      {modal}
      <div id="modal-root"/>
      <SpeedInsights/>
    </main>
    <Footer/>
    </body>
    </html>
  );
}
