import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import "./globals.scss"
import {Header} from "@/widgets/Header/Header"
import {Footer} from "@/widgets/Footer/Footer";

const roboto = Roboto({
  weight: ["300", "400", "700", "900"],
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "МедЭксперт",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {/*<Header />*/}
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
